### ISSUE TITLE
Guide for windows users to install abcpy

### ISSUE THREAD

**Issue by Song921012** [eth-cscs/abcpy#105]
To start with, appreciate the eth-cscs team's excellent work on abcpy. I have been struggling for installing abcpy on windows for a real long time.  For windows users, the installation problem here is that abcpy requires glmnet, and glmnet needs a Fortran compiler. One method mentioned by eth-cscs team is installing abcpy without glmnet, see link https://github.com/eth-cscs/abcpy/issues/97#issuecomment-981919114. Here I share my successful experience on installing abcpy with glmnet. I use conda to manage my environment.

# Step One: Install mingw-64. (It has fortran compiler)

`conda install -c conda-forge prophet` 

I installed prophet package before, it helps me install mingw64.  
You can install mingw-64 in conda by your own way.

# Step Two: Install mpi4py. Microsoft MPI

`conda install -c conda-forge  mpi4py msmpi`

# Step Three. Install glmnet and abcpy

`pip install glmnet abcpy`

You will successfully compile and install glmnet, also succefully install abcpy. However,  you still can not import glmnet succefully. you will meet.

Error `DLL load failed while importing _glmnet` 

You need last step.

# Step Four:  Copy DLL to path
find the dll `Anaconda\Lib\site-packages\_glmnet\.lib\*.dll`  and copy to `Anaconda\Lib\site-packages`.

**Comment by LoryPack** [comment]
Hello, thank you very much for sharing that! I am glad you were able to install ABCpy on Windows and I hope that was not too painful!

I will soon link your solution in the ABCpy documentation, so that other interested people can find it.

**Comment by LoryPack** [comment]
Would you mind writing the specific Windows version you used?

**Comment by statrita2004** [comment]
Thanks a lot.
