### ISSUE TITLE
sklearn depreciation

### ISSUE THREAD

**Issue by JoeZiminski** [eth-cscs/abcpy#110]
Many thanks for this excellent package!

sklearn is being depreciated according to this [depreciation schedule](https://github.com/scikit-learn/sklearn-pypi-package). It is currently in the rep's requirements.txt file and can cause build errors (depending on what time the package is installed, re: depreciation schedule). It would be great if this could be removed from the requirements and sklearn imports ported to scikit-learn.

Cheers!
Joe

**Comment by statrita2004** [comment]
Thanks a lot Joe. Now removed sklearn from requirements.txt. Cheers, Rito
