### ISSUE TITLE
Deprecation warnings glmnet

### ISSUE THREAD

**Issue by statrita2004** [eth-cscs/abcpy#14]
>>> from abcpy.distances import LogReg
/users/mvalle/spark/py/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
 "This module will be removed in 0.20.", DeprecationWarning)

**Comment by mschoengens** [comment]
Fixed in 0.2.1
