### ISSUE TITLE
SABC returns the same set of parameters in the journal case of full_output=1

### ISSUE THREAD

**Issue by dalmo1991** [eth-cscs/abcpy#40]
I'm running SABC with full_output=1 and the parameters list of arrays in the Journal has, in each re-sample, the same arrays of parameters.
Called a_i the array of parameters generated in the i-th step of the algorithm (i from 1 to #steps), in the case of 5 steps with re-sample after the 2nd the results is

[a_2, a_2, a_5, a_5, a_5]

I run the code in debug and, looking inside the journal.add_parameters function, each step it's called the journal.parameters list becomes:
[a_1]
[a_2, a_2]
[a_2, a_2, a_3]
[a_2, a_2, a_4, a_4]
[a_2, a_2, a_5, a_5, a_5]

**Comment by statrita2004** [comment]
How Marko: Which version of ABCpy are you using? Please let me know, I will have a look.

**Comment by dalmo1991** [comment]
pip3 show abcpy
Name: abcpy
Version: 0.5.1
Summary: A framework for approximate Bayesian computation (ABC) that speeds up inference by parallelizing computation on single computers or whole clusters.
Home-page: https://github.com/eth-cscs/abcpy
Author: The abcpy authors
Author-email: UNKNOWN
License: BSD-3
Location: /usr/local/lib/python3.5/dist-packages
Requires: coverage, numpy, sklearn, glmnet, sphinx-rtd-theme, sphinx, scipy

**Comment by statrita2004** [comment]
Thanks I will have a look. Thanks for pointing out.

**Comment by dalmo1991** [comment]
Can you also add the distance as a feature in the journal? I mean, for each sample we get also the distance between obs and sim data
thanks

**Comment by statrita2004** [comment]
Yes. That is possible. But we are constrained with time regarding developments. Can you please fork a branch and contribute this feature. Also you may correct the error and contribute. We will really appreciate any sorts of help.

**Comment by dalmo1991** [comment]
I don't have time to fix the bug on github because I'm leaving today for holidays. But I've found the solution.

When you append a np.array to a list you aren't copying the values but just appending a "pointer" (I don't know how to call it in python). So when you change the np.array all its references in the list get changed.

A solution could be appending a copy (method copy()) of the array instead of the pointer.

self.parameters.append(params.copy())

I think there can be the same bug in other places, like when we store the weights.
I can fix the bug in 3 weeks, after holidays.

**Comment by statrita2004** [comment]
Thanks Marko. Yes, that's one issue. There are some other additional issues too. We have fixed it and added the distances to output also now. We will release these updates in a week or two as a new release 0.5.2.

**Comment by statrita2004** [comment]
The bug has been fixed in release 0.5.2 and the distance for SABC are also now added to journal files. So I am closing this issue. Thanks a lot for pointing the issue.
