### ISSUE TITLE
Issue with multivariate parameters

### ISSUE THREAD

**Issue by uweschmitt** [eth-cscs/abcpy#56]
I have a problem using a multivariate distribution for the parameters of a model.

The following example is the smallest example I can come up to reproduce my issue:

```
import numpy as np
from abcpy.backends import BackendDummy as Backend
from abcpy.continuousmodels import (InputConnector, MultivariateNormal,
                                    ProbabilisticModel)
from abcpy.distances import Euclidean
from abcpy.inferences import PMCABC
from abcpy.perturbationkernel import DefaultKernel
from abcpy.statistics import Identity
from numpy.random import multivariate_normal

mu = [0, 0]
cov = [[2, 0.5], [0.5, 2]]

data = multivariate_normal(mu, cov, 100).tolist()

class IdentityModel(ProbabilisticModel):
    def __init__(self, parameters, name):
        parameters = InputConnector.from_list(parameters)
        super().__init__(parameters, name)

    def forward_simulate(self, input_values, k, rng=np.random.RandomState()):
        # Extract the input parameters
        return [input_values]

    def _check_input(self, parameters):
        return True

    def _check_output(self, parameters):
        return True

    def pdf(self, input_values, x):
        raise NotImplementedError

    def get_output_dimension(self):
        return len(self.x)


statistics = Identity(2, False)
distance = Euclidean(statistics)

mv = MultivariateNormal([mu, cov])

model = IdentityModel([mv], "model")
kernel = DefaultKernel([mv])
backend = Backend()


sampler = PMCABC([model], [distance], backend, kernel, seed=1)

T, n_sample, n_samples_per_param = 2, 100, 1

eps_arr = np.array([500])
epsilon_percentile = 10

journal = sampler.sample(
    [data], T, eps_arr, n_sample, n_samples_per_param, epsilon_percentile, full_output=1
)
```

The error message I'm concerned about is:
```
$ python multivar.py
Traceback (most recent call last):
  File "multivar.py", line 58, in <module>
    [data], T, eps_arr, n_sample, n_samples_per_param, epsilon_percentile, full_output=1
  File "/Users/uweschmitt/Projects/scripts_uwe/abcpy_examples/venv37/lib/python3.7/site-packages/abcpy/inferences.py", line 488, in sample
    self.accepted_parameters_manager.get_accepted_parameters_bds_values(kernel.models))
  File "/Users/uweschmitt/Projects/scripts_uwe/abcpy_examples/venv37/lib/python3.7/site-packages/abcpy/acceptedparametersmanager.py", line 147, in get_accepted_parameters_bds_values
    accepted_bds_values[i].append(self.accepted_parameters_bds.value()[i][index])
IndexError: index 1 is out of bounds for axis 0 with size 1
```
Looks like there are some indexing issues for the non-scalar distribution.

**Comment by statrita2004** [comment]
Yes! Indeed there was an error. I have now fixed the error in branch FixingHD. Also, the model you wrote needed some fixes. Here is the fixed version of your example below. Can you please run this in FixingHD branch and let me know whether your error got fixed or not? Then I will release a new version with the fix.

import numpy as np
from abcpy.backends import BackendDummy as Backend
from abcpy.probabilisticmodels import Continuous
from abcpy.continuousmodels import (InputConnector, MultivariateNormal, ProbabilisticModel)
from abcpy.distances import Euclidean
from abcpy.inferences import PMCABC
from abcpy.perturbationkernel import DefaultKernel
from abcpy.statistics import Identity
from numpy.random import multivariate_normal as mnp

class IdentityModel(ProbabilisticModel, Continuous):
    def __init__(self, parameters, name='Identity Normal'):
        if not isinstance(parameters, list):
            raise TypeError('Input for Identity has to be of type list.')
        if len(parameters) is not 1:
            raise ValueError('Input for Identity has to be of length 1.')

        input_values = parameters[0]
        if isinstance(input_values, list):
            self._dimension = len(input_values)
        elif isinstance(input_values, ProbabilisticModel):
            self._dimension = input_values.get_output_dimension()

        input_parameters = InputConnector.from_list(parameters)

        super(IdentityModel, self).__init__(input_parameters, name)
        self.visited = False

    def forward_simulate(self, input_values, k, rng=np.random.RandomState()):
        # Extract the input parameters
        return [np.array(input_values).reshape(-1,)]

    def _check_input(self, parameters):
        return True

    def _check_output(self, parameters):
        return True

    def pdf(self, input_values, x):
        raise NotImplementedError

    def get_output_dimension(self):
        return self._dimension


mu = [0, 0]
cov = [[2, 0.5], [0.5, 2]]

mv = MultivariateNormal([mu, cov])

statistics = Identity(2, False)
distance = Euclidean(statistics)

model = IdentityModel([mv], "Identitymodel")
kernel = DefaultKernel([mv])
backend = Backend()

sampler = PMCABC([model], [distance], backend, kernel, seed=1)

T, n_sample, n_samples_per_param = 2, 100, 1

eps_arr = np.array([500])
epsilon_percentile = 10

data = mnp(mu, cov, 100).tolist()

journal = sampler.sample([data], T, eps_arr, n_sample, n_samples_per_param, epsilon_percentile, full_output=1)

print(journal.posterior_mean())

**Comment by uweschmitt** [comment]
I get

```
$ python multivar.py
Traceback (most recent call last):
  File "multivar.py", line 63, in <module>
    model = IdentityModel([mv], "Identitymodel")
  File "/Users/uweschmitt/Projects/abcpy/abcpy/probabilisticmodels.py", line 284, in __init__
    raise TypeError('Input parameters are of wrong type.')
TypeError: Input parameters are of wrong type.
```

But I had to fix some indentation issues with your solution. Could you please reformat the full code as one big code section ?

**Comment by statrita2004** [comment]
Here is the code as code-block. This should run. 

<pre>
import numpy as np
from abcpy.backends import BackendDummy as Backend
from abcpy.probabilisticmodels import Continuous
from abcpy.continuousmodels import (InputConnector, MultivariateNormal, ProbabilisticModel)
from abcpy.distances import Euclidean
from abcpy.inferences import PMCABC
from abcpy.perturbationkernel import DefaultKernel
from abcpy.statistics import Identity
from numpy.random import multivariate_normal as mnp

class IdentityModel(ProbabilisticModel, Continuous):
    def __init__(self, parameters, name='Identity Normal'):
        if not isinstance(parameters, list):
            raise TypeError('Input for Identity has to be of type list.')
        if len(parameters) is not 1:
            raise ValueError('Input for Identity has to be of length 1.')

        input_values = parameters[0]
        if isinstance(input_values, list):
            self._dimension = len(input_values)
        elif isinstance(input_values, ProbabilisticModel):
            self._dimension = input_values.get_output_dimension()

        input_parameters = InputConnector.from_list(parameters)

        super(IdentityModel, self).__init__(input_parameters, name)
        self.visited = False

    def forward_simulate(self, input_values, k, rng=np.random.RandomState()):
        # Extract the input parameters
        return [np.array(input_values).reshape(-1,)]

    def _check_input(self, parameters):
        return True

    def _check_output(self, parameters):
        return True

    def pdf(self, input_values, x):
        raise NotImplementedError

    def get_output_dimension(self):
        return self._dimension


mu = [0, 0]
cov = [[2, 0.5], [0.5, 2]]

mv = MultivariateNormal([mu, cov])

statistics = Identity(2, False)
distance = Euclidean(statistics)

model = IdentityModel([mv], "Identitymodel")
kernel = DefaultKernel([mv])
backend = Backend()

sampler = PMCABC([model], [distance], backend, kernel, seed=1)

T, n_sample, n_samples_per_param = 2, 100, 1

eps_arr = np.array([500])
epsilon_percentile = 10

data = mnp(mu, cov, 100).tolist()

journal = sampler.sample([data], T, eps_arr, n_sample, n_samples_per_param, epsilon_percentile, full_output=1)

print(journal.posterior_mean())
</code></pre>

**Comment by statrita2004** [comment]
For further clarification, here is a little more complicated code. There was still some more bugs, which I needed to fix to adapt ABCpy for multivariate variables. Please have a look and let me know whether you can spot any further bugs. (Run the following after git pull in FixingHD branch):

<pre><code>import numpy as np
from abcpy.backends import BackendDummy as Backend
from abcpy.continuousmodels import (InputConnector, MultivariateNormal, Uniform, ProbabilisticModel, Continuous)
from abcpy.distances import Euclidean
from abcpy.inferences import PMCABC
from abcpy.perturbationkernel import DefaultKernel
from abcpy.statistics import Identity
from numpy.random import multivariate_normal

import logging
logging.basicConfig(level=logging.DEBUG)

mu = [0, 0]
cov = [[2, 0.5], [0.5, 2]]

data = multivariate_normal(mu, cov, 100).tolist()


class IdentityModel(ProbabilisticModel):
    def __init__(self, parameters, name):
        parameters = InputConnector.from_list(parameters)
        super().__init__(parameters, name)

    def forward_simulate(self, input_values, k, rng=np.random.RandomState()):
        # Extract the input parameters
        return [input_values]

    def _check_input(self, parameters):
        return True

    def _check_output(self, parameters):
        return True

    def pdf(self, input_values, x):
        raise NotImplementedError

    def get_output_dimension(self):
        return len(self.x)


class Dirichlet(ProbabilisticModel, Continuous):
    def __init__(self, parameters, name='Dirichlet'):

        if not isinstance(parameters, list):
            raise TypeError('Input for Dirichlet has to be of type list.')
        if len(parameters) < 2:
            raise ValueError('Input for Dirichlet has to be of length 2')

        self._dimension = len(parameters[0])  # 5
        input_parameters = InputConnector.from_list(parameters)  # dovrebbe trasformare i parametri in unica lista
        super(Dirichlet, self).__init__(input_parameters, name)
        self.visited = False

    def _check_input(self, input_values):
        return True

    def _check_output(self, parameters):
        return True

    def forward_simulate(self, input_values, k, rng=np.random.RandomState()):
        dim = self.get_output_dimension()
        alphas = np.array(input_values[0:dim])
        edges = np.array(input_values[dim:])
        result = []
        for ind in range(k):
            result.append((rng.dirichlet(alphas, size=1)[0]) * rng.uniform(low=edges[0], high=edges[1], size=1))
        return [np.array(x).reshape(-1, ) for x in result]

    def get_output_dimension(self):
        return self._dimension

    def pdf(self, input_values, x):
        dim = self.get_output_dimension()
        pdf_value = 0.5
        return pdf_value


statistics = Identity(2, False)
distance = Euclidean(statistics)

dir = Dirichlet([[1., 1.], [5., 15.]])

mv = Uniform([[1], [2]])

ll = Uniform([[1], [2]])

model = IdentityModel([ll, dir, mv], "model")

kernel = DefaultKernel([ll, dir, mv])
backend = Backend()

sampler = PMCABC([model], [distance], backend, kernel, seed=1)

T, n_sample, n_samples_per_param = 3, 100, 1
eps_arr = np.array([500])
epsilon_percentile = 10

journal = sampler.sample([[np.array([1.2, 1, 1.2,1.3]).reshape(-1,)]], T, eps_arr, n_sample, n_samples_per_param, epsilon_percentile, full_output=1)
</code></pre>

**Comment by uweschmitt** [comment]
:ok_hand: works ! thank you very much.

Will this fix be merged to master soon ?

**Comment by statrita2004** [comment]
We have now merged the new features and some more improvements in the new release of v0.5.6. I consider this issue resolved and close the issue. Thanks.
