### ISSUE TITLE
MPI required?

### ISSUE THREAD

**Issue by rheiland** [eth-cscs/abcpy#66]
Is MPI a requirement for abcpy? I didn't see that in the Installation page. When I attempt to pip install it, I get:
```
    _configtest.c:2:10: fatal error: 'mpi.h' file not found
    #include <mpi.h>
             ^~~~~~~
    1 error generated.
```

**Comment by statrita2004** [comment]
Hello, ABCpy depends on some Python packages listed [here](https://github.com/eth-cscs/abcpy/blob/master/requirements.txt). We do not list their dependencies separately, but those should be satisfied. So more specifically speaking: 
- mpi4py package needs MPI installed. Also all the parallelization in ABCpy is done using MPI. 
- glmnet package needs availability of a Fortran compiler.
