### ISSUE TITLE
SABC does not save the right distance in the journal after resampling

### ISSUE THREAD

**Issue by dalmo1991** [eth-cscs/abcpy#68]
**NOTE: I will refer to the current master version of the file `abcpy/inferences.py`**

SABC algorithm has 2 distances inside: `distances` that is the value returned by the `Distance` class (relevant number when analyzing the results of a simulation) and `smooth_distances` which is used basically everywhere in the algorithm.

The problem is that the resampling (`if` at line 1230) is (correctly) done using the `smooth_distances` but only this value is updated afterwards (line 1236).

This creates the problem that `distances` does not change during the resampling and, from that moment on, this wrong matrix is saved in the journal at every iteration.

**Possible bug fix**
Add after line 1236 the following line
```
distances = distances[index_resampled]
```

**Comment by LoryPack** [comment]
Hi, thanks for spotting that! I will soon open a pull request fixing that. It looks like what you suggest would do the job.

**Comment by LoryPack** [comment]
This has been merged in the develop branch; it will be merged in the master branch by the next release, which is planned soon.

Thanks again!
