### ISSUE TITLE
 error: extension '_glmnet' has Fortran sources but no Fortran compiler found

### ISSUE THREAD

**Issue by thisismihir** [eth-cscs/abcpy#88]
Hey so I was installing glmnet by using pip install glmnet, also tried by using the wheel file. I'm getting the following error:
  Building wheel for glmnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: '..\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'..\pip-install-z85qz6m4\\glmnet_7f7a7f35ff654772862ef9f8358e2a4e\\setup.py'"'"'; __file__='"'"'..\pip-install-z85qz6m4\\glmnet_7f7a7f35ff654772862ef9f8358e2a4e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LENOVO~1\AppData\Local\Temp\pip-wheel-_0ejym25'
       cwd: ..\pip-install-z85qz6m4\glmnet_7f7a7f35ff654772862ef9f8358e2a4e\
  Complete output (56 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "_glmnet" sources
  f2py options: []
    adding 'build\src.win-amd64-3.6\build\src.win-amd64-3.6\glmnet\fortranobject.c' to sources.
    adding 'build\src.win-amd64-3.6\build\src.win-amd64-3.6\glmnet' to include_dirs.
  build_src: building npy-pkg config files
  running build_py
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\glmnet
  copying glmnet\doc.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\errors.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\linear.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\logistic.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\scorer.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\util.py -> build\lib.win-amd64-3.6\glmnet
  copying glmnet\__init__.py -> build\lib.win-amd64-3.6\glmnet
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
  warning: build_ext: f77_compiler=None is not available.

  building '_glmnet' extension
  error: extension '_glmnet' has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for glmnet
  Running setup.py clean for glmnet
Failed to build glmnet
Installing collected packages: glmnet
    Running setup.py install for glmnet ... error
    ERROR: Command errored out with exit status 1:

     building '_glmnet' extension
    error: extension '_glmnet' has Fortran sources but no Fortran compiler found
    
    Can you help me with this?

**Comment by statrita2004** [comment]
Hi, This is an error you getting while trying to install glmnet package. It tells you that in your machine the python package installer can not find a Fortran compiler. If you are using an Windows machine (this doesn't happen in Linux or Mac), this is a known problem and some workarounds are available online. But as this is not an issue related to ABCpy package, I will close this issue and recommend your to raise the same issue at glmnet package providers. They may be able to help you.
